from app.models import Analysis


def build_report(analysis: Analysis, artifacts: dict[str, object] | None = None) -> str:
    confidence = round(analysis.confidence * 100)
    artifacts = artifacts or {}
    bounding_boxes = artifacts.get("bounding_boxes", [])
    segmentation_mask_paths = artifacts.get("segmentation_mask_paths", [])
    engine = dict(artifacts.get("engine", {}))

    box_lines = "\n".join(
        f"- {box['label']} ({round(float(box['confidence']) * 100)}%) [{box['x_min']}, {box['y_min']}] to [{box['x_max']}, {box['y_max']}]"
        for box in bounding_boxes
    ) or "- No bounding boxes recorded"

    return f"""OncoVision AI Research Report

Analysis ID: {analysis.id}
Modality: {analysis.modality}
Possible finding: {analysis.prediction}
Confidence: {confidence}%

Explanation:
{analysis.explanation}

Engine:
- Classifier: {engine.get("classifier", "unknown")}
- Detector: {engine.get("detector", "unknown")}
- Segmenter: {engine.get("segmenter", "unknown")}

Bounding boxes:
{box_lines}

Segmentation masks:
- {len(segmentation_mask_paths)} mask file(s) generated

Export note:
- Annotated image and segmentation mask files were produced by the modular inference pipeline.

Important limitation:
This report was generated by a research-only modular AI pipeline for research and educational use only.
AI output is not a medical diagnosis, treatment recommendation, or clinical decision support output.
"""
